baseURL = 'https://csigildea.github.io/'
languageCode = 'en-us'
title = 'Conor Gildea'
theme = "anatole"
enableEmoji = true
enableRobotsTXT = true

[params]
displayMode = "light"
doNotLoadAnimations = true
contentratio = 0.7
customCss = ["css/custom.css"]
mainSections = []
enableMediumZoom = true
title = "Conor Gildea"
author = "Conor Gildea"
profilePicture = "images/profile.jpg"
description = """
<b>Scaling Gemini at Google ðŸ¤–</b>

"""

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/csigildea"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/csigildea"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/csigildea"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:publicconor@gmail.com?subject=[Personal Website] <Topic>"

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Projects"
  weight = 200
  identifier = "projects"
  url = "/projects/"

  [[menu.main]]
  name = "Bay Area Lists"
  weight = 300
  identifier = "baylists"
  url = "/baylists/"

  [[menu.main]]
  name = "Dublin Lists"
  weight = 400
  identifier = "dublists"
  url = "/dublists/"

  [[menu.main]]
  name = "Back Exercises"
  weight = 500
  identifier = "back"
  url = "/back/"

  [[menu.main]]
  name = "Coffee Setups"
  weight = 600
  identifier = "coffee"
  url = "/coffee/"